name: Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Protoc
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: protobuf-compiler protobuf-c-compiler
        version: 1.0

    - name: Generate protobuf
      run: |
        protoc --c_out=deps/livekit-protocol-generated -I=./deps/livekit-protocol livekit_rtc.proto livekit_models.proto

    - name: Set Env variables
      run: |
        sed -i '1s;^;set(ENV{WIFI_SSID} a)\n;' CMakeLists.txt
        sed -i '1s;^;set(ENV{WIFI_PASSWORD} a)\n;' CMakeLists.txt
        sed -i '1s;^;set(ENV{LIVEKIT_URL} a)\n;' CMakeLists.txt
        sed -i '1s;^;set(ENV{SKIP_PROTOBUF_GENERATE} a)\n;' CMakeLists.txt

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.3
        target: esp32s3
