name: Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        target: [esp32s3, linux]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build
      run: |
        docker run -v $PWD:/project -w /project -u 0 \
        -e HOME=/tmp -e WIFI_SSID=A -e WIFI_PASSWORD=B -e LIVEKIT_URL=X -e LIVEKIT_TOKEN=Y \
        espressif/idf:latest \
        /bin/bash -c 'apt update && apt install -y protobuf-compiler protobuf-c-compiler && idf.py --preview set-target ${{ matrix.target }} && idf.py build'
      shell: bash
